codetest/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resource :posts
  resource :comments
  
  root :to => 'sessions#start'
  
  match '/signin', to: 'sessions#create', via: :post
  match '/session', to: 'sessions#create', via: :post
  match '/signup', to: 'users#new', via: :get
  match '/signout', to: 'sessions#destroy', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/users/new', to: 'users#create', via: :post
end

codetest/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

codetest/app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

codetest/app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments
    
    #validates :title, presence: true,
    #length: { minimum: 4, maximum: 200 }
    
    #validates :text, presence: true,
    #length: { maximum: 1000 }
    #validates :user_id, presence: true
end

codetest/app/models/user.rb
class User < ApplicationRecord
    attr_accessor :firstname, :lastname, :email, :username, :password, :password_confirmation, :token
    has_secure_password
    has_many :posts
    has_many :comments
    
    attr_accessor :updating_password
    
    before_save { |user|
    user.email = email.to_s.downcase
    }
    before_create :create_token
    
    #validates :firstname, presence: true, length: {:maximum => 50}
    #validates :lastname, presence: true, length: {:maximum => 50}
    #validates :username, presence: true, length: {:maximum => 50}

    #VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    #validates :email, presence: true,
    #format: {:with => VALID_EMAIL_REGEX},
    #uniqueness: {:case_sensitive => false}
    validates :password_digest, presence: {:message => 'Please confirm your password'}, :if => :updating_password
    
    def should_validate_password?
        updating_password
    end
    
    
    private
    
    def create_token
        self.token = SecureRandom.urlsafe_base64
    end
end

codetest/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

codetest/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_filter :require_login
    def show
        require 'open-uri'
        post = Post.find(params[:id])
        comment_list = Comment.where("post_id = ?", post.id)
    end
                                                             
    def new
        user = @current_user
        post = Post.find(params[:id])
        comment = Comment.new
        comment.text = params[:text].to_s
        comment.post_id = post.id
        comment.user_id = user.id
        if comment.save!
            redirect_to comments_path
        else
            respond_to do |format|
                format.js { render :action => 'errors.js.ejb' }
            end
        end
    end
                                                             
    private
    def require_login
        unless signed_in?
        redirect_to "/"
    end
end

codetest/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :require_login
    def show
        require 'open-uri'
        @post_list = Post.order('user_id')
    end
    
    def create
        @current_user = User.find_by_token(cookies[:remembered_token])
        if @current_user
            post = Post.new
            post.title = params[:title].to_s
            post.text = params[:text].to_s
            post.user_id = @current_user.id
            post.save!
        end
        render 'show'
    end
    
    private
    def require_login
        @current_user = User.find_by_token(cookies[:remembered_token])
        if @current_user
            return @current_user
        else
            redirect_to "/"
        end
    end
end

codetest/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def start
        logger.info "session#start"
        @current_user = User.find_by_token(cookies[:remembered_token])
        if @current_user
            redirect_to posts_path
        else
            render 'new'
        end
        
    end
    
    def new
        
        logger.info "sessions#new"
        
    end
    
    def create
        user = User.find_by_email(params[:email])
        if user && user.authenticate(params[:password])
            @current_user = user
            cookies[:token] = user.token
            redirect_to posts_path
        else
            render 'new'
        end
    end
    
    def destroy
        @current_user = nil
        cookies.delete[:token]
        redirect_to root_path
    end
end

codetest/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
    end
    
    def create
        logger.info "users_controller new **** "
        
        user = User.new
        user.email = params[:email].to_s
        user.firstname = params[:firstname].to_s
        user.lastname = params[:lastname].to_s
        user.username = params[:username].to_s
        user.password_digest = BCrypt::Password.create(params[:password].to_s)
        if user.save!
            redirect_to posts_path(:id => user.id)
            else
            respond_to do |format|
                format.js { render :action => 'errors.js.ejb' }
            end
        end
    end
end

codetest/app/helpers/application_helper.rb
module ApplicationHelper
end

codetest/app/helpers/comments_helper.rb
module CommentsHelper
end

codetest/app/helpers/posts_helper.rb
module PostsHelper
end

codetest/app/helpers/sessions_helper.rb
module SessionsHelper
    module SessionsHelper
        def sign_in(user)
            # If the user doesn't have a remember_token, add it back in.
            if user.token.nil?
                user.token = SecureRandom.urlsafe_base64
                user.save
            end
            cookies.permanent[:token] = user.token
            current_user = user
        end
        
        def signed_in?
            !@current_user.nil?
        end
        
        def current_user=(user)
            @current_user = user
        end
        
        def current_user
            if @current_user
                return @current_user
            elsif !cookies[:token].nil?
                @current_user = User.find_by_token(cookies[:token])
                return @current_user
            end
            return nil
        end
        
        def sign_out
            @current_user = nil
            cookies.delete(:token)
        end
    end

end

codetest/app/helpers/users_helper.rb
module UsersHelper
end

codetest/app/views/comments/_comment.html.erb
<%= link_to comment.name, comment_path(comment) %>

codetest/app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'shared/errors', obj: @comment %>

<div class="row">
<div class="col-xs-12">
<%= form_for(@comment, :html => {class: "form-horizontal", role: "form"}) do |f| %>
<%= f.hidden_field :post_id %>
<div class="form-group">
<div class="control-label col-sm-2">
<%= f.label :comment %>
</div>

<div class="col-sm-8">
<%= f.text_area :comment, rows: 3, class: "form-control", placeholder: "Please enter a comment", autofocus: true %>
</div>
</div>

<div class="form-group">
<div class="center col-sm-offset-1 col-sm-10">
<%= f.submit class: "btn btn-primary btn-lg" %>
</div>
</div>
<% end %>

codetest/app/views/comments/show.html.erb
<div class="tab-pane" id="comment">

<div>
<p>
<strong>Title:</strong>
<%= @article.title %>
</p>

<p>
<strong>Text:</strong>
<%= @article.text %>
</p>
<% if @post.user_id = @user_id %>
<%= link_to 'Edit', post_update_path %>
<% end %>
</div>

<div>
<%= form_tag ('/comment/index') do %>
<%= hidden_field_tag 'user_id', @user.id %>
<%= hidden_field_tag 'post_id', @post.id %>
<%= text_field_tag 'username', nil, :placeholder => 'User', :clnameass => 'span2' %>
<%= text_field_tag 'text', nil, :placeholder => 'Text', :class => 'span20' %>
<%= text_field_tag 'date', nil, :placeholder => 'Date yyyyMMdd', :class => 'span2' %>
<%= submit_tag "Search", :name => nil %>
<% end %>
</div>
<table class='table table-bordered table-striped'>
<thead>
<tr>
<th class='member-table-th'> Username</th>
<th class='member-table-th'> Text</th>
<th class='member-table-th'> Date</th>
</tr>
</thead>
<tbody>
<% if !@comment_list.nil? %>
<% @comment_list.each do |m| %>
<% if !m.nil? %>
<tr>
<td class='member-table-td'>
<%= m.username %>
</td>
<td class='member-table-td'>
<p>
<%= m.text.html_safe %>
</p>
</td>
<td class='member-table-td'>
<%= m.updated_at.in_time_zone(m.time_zone.to_s).strftime('%b %d, %Y %H:%M') %>
</td>
<td class='member-table-td'>
<% if m.user_id == @user.id %>
<%= link_to "Update", '/comment/update?id=' + m.id.to_s + '&user_id=' + @user.id.to_s %>
&nbsp;&nbsp;
<%= link_to "Delete", comment_delete_path(:id => m.id, :user_id =>@user.id), :method => :delete, :confirm => "Permenantly Delete This Comment?" %>
<% end %>
</td>
</tr>
<% end %>
<% end %>
</tbody>
</table>

<%= will_paginate @post_list, :class => 'apple_pagination' %>
<br>
<%= link_to "Add Comment", <script> function() { var modal = document.getElementById('newCommentModal');  %>
<%= modal.style.display = "block";} </script> %>
}
<script>
$("form").submit(function() {
$.post($(this).attr('action'), $(this).serializeArray());
var modal = document.getElementById('newCommentModal');
modal.style.display = "none";
});
</script>

<!-- The New Comment Modal -->
<div id="newCommentModal" class="modal">
<h1>New Comment</h1>

<%= render 'shared/errors', obj: @comment %>

<div class="row">
<div class="col-xs-12">
<%= form_for(@comment, :html => {class: "form-horizontal", role: "form"}) do |f| %>
<%= f.hidden_field :post_id %>
<div class="form-group">
<div class="control-label col-sm-2">
<%= f.label :comment %>
</div>

<div class="col-sm-8">
<%= f.text_area :comment, rows: 3, class: "form-control", placeholder: "Please enter a comment", autofocus: true %>
</div>
<!-- The Close Button -->
<span class="close" onclick="document.getElementById('newCommentModal').style.display='none'">&times;</span>
</div>

<div class="form-group">
<div class="center col-sm-offset-1 col-sm-10">
<%= f.submit class: "btn btn-primary btn-lg" %>
</div>
</div>
<% end %>

codetest/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codetest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

codetest/app/views/posts/show.html.erb
<div class="tab-pane" id="post">

<table class='table table-bordered table-striped'>
<thead>
<tr>
<th> Title*************</th>
<th> User</th>
<th> Date</th>
<th> Action</th>
</tr>
</thead>
<tbody>
<% if @post_list %>
<% @post_list.each do |m| %>
<% if m %>
<tr>
<td>
<%= m.title.html_safe %>
</td>
<td>
<p>
<% user = User.find_by_id(m.user_id) %>
<%= user.username %>
</p>
</td>
<td>
</td>
<td>
<%= link_to "Details", /comments/show?id=' + m.id.to_s + '&user_id=' + user.id.to_s %>
</td>
</tr>
<% end %>
<% end %>
<% end %>
</tbody>
</table>
<% if @post_list %>
<% end %>
<br>
</div>
<div>
<%= form_for :post do |f| %>
<p>
<%= f.label :title %><br>
<%= f.text_field :title %>
</p>

<p>
<%= f.label :text %><br>
<%= f.text_area :text %>
</p>

<p>
<%= f.submit %>
</p>
<% end %>
</div>

codetest/app/views/users/new.html.erb
<%= provide(:title, 'Sign up') %>
<h1> Sign up</h1>

<div>
  <div >
    <p> Create an account: </p>
  </div>
</div>

<div>
  <div>
<%= form_for :users_new_path do |f| %>

      <%= f.label :firstname %>
      <%= f.text_field :firstname, :class => "text", style: "height:40px" %>
        <br><br>
      <%= f.label :lastname %>
      <%= f.text_field :lastname, :class => "text", style: "height:40px" %>
        <br><br>
      <%= f.label :username %>
      <%= f.text_field :username, :class => "text", style: "height:40px" %>
      <br><br>
      <%= f.label :email %>
      <%= f.text_field :email, :class => "text", style: "height:40px" %>
        <br><br>
      <%= f.label :password %>
      <%= f.password_field :password, :class => "text", style: "height:40px" %>
        <br><br>
      <%= f.label :password_confirmation, "Password Confirmation" %>
      <%= f.password_field :password_confirmation, :class => "text", style: "height:40px" %>
        <br><br>
     
      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>